name: Study
version: ${project.version}
main: me.saidbysolo.study.Study
commands:
  setCorrectLocation:
    description: Yes
  setNegativeLocation:
    description: No
  start:
    description: start
  test:
    description: test