name: Study
version: ${project.version}
main: me.saidbysolo.study.Study
commands:
  setcorrectposition:
    description: Yes
  setnegativeposition:
    description: No
  start:
    description: start
  test:
    description: test

